version: "3"
services:
  mongo:
    image: mongo
    ports:
    - "27017:27017"
  backend:
    image: docker.io/joellord/mern-k8s-back
    depends_on:
    - mongo 
    ports:  
    - "5000:5000" 
  client:
    image: docker.io/joellord/mern-k8s-front
    ports:
      - "8080:80"