version: "3"
services:
  backend:
    image: docker.io/andresmunguia/mern-k8s-back
    environment: 
      - CONN_STR=mongodb+srv://mern-k8s:mern-k8s@mern-k8s.gci7rew.mongodb.net/?retryWrites=true&w=majority
      - PORT=5000
    ports:  
      - "5000:5000" 
  client:
    image: docker.io/andresmunguia/mern-k8s-front
    environment: 
      - BASE_URL=http://localhost:5000
    ports:
      - "8080:80"