name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build frontend Docker image.
      run: docker build . --file ./front/Dockerfile --tag mern-k8s-front:latest
    - name: Build backend Docker image.
      run: docker build . --file ./back/Dockerfile --tag mern-k8s-back:latest
