name: Docker Image CI
      
on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build & push frontend Docker image.
      working-directory: ./front
      run: |
            docker build . --file Dockerfile --tag andresmunguia/mern-k8s-front:latest
            docker push andresmunguia/mern-k8s-front
    - name: Build & push backend Docker image.
      working-directory: ./back
      run: |
            docker build . --file ./back/Dockerfile --tag andresmunguia/mern-k8s-back:latest
            docker push andresmunguia/mern-k8s-back
